daily:
- enabled: false
  name: sign_in
  priority: 1
  repeat:
    at_time: 00:00
    times: 1
    type: daily
- enabled: false
  name: daily_rewards
  priority: 1
  repeat:
    at_time: 00:00
    times: 1
    type: daily
default_order:
- daily
- permanent
- special
- event
event: []
permanent: []
special:
- enabled: false
  execution_rule:
    mode: count
    value: 1
  name: home_scan
  priority: 8
  repeat:
    type: once
- enabled: false
  execution_rule:
    mode: time
    value: 59
  name: test_list
  priority: 10
  repeat:
    max_daily: 3
    time_end: '23:59'
    time_start: 00:00
    type: daily
