daily:
- enabled: false
  name: sign_in
  priority: 1
  repeat:
    at_time: 00:00
    times: 1
    type: daily
- enabled: false
  name: daily_rewards
  priority: 1
  repeat:
    at_time: 00:00
    times: 1
    type: daily
default_order:
- daily
- permanent
- special
- event
event: []
permanent: []
special:
- enabled: true
  name: home_scan
  priority: 8
  repeat:
    max_daily: 1
    times: 1
    type: once
